# Generated by Django 5.0.6 on 2024-07-05 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postcommentmodel_commentlikemodel_postmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcommentmodel',
            options={'ordering': ('comment',), 'verbose_name': 'post comment', 'verbose_name_plural': 'post comments'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.postmodel'),
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
