# Generated by Django 5.0.6 on 2024-07-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postcommentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcommentmodel',
            options={'ordering': ('-comment',), 'verbose_name': 'post comment', 'verbose_name_plural': 'post comments'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
